import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Prrovider";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Suspense } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PsiFi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense>
          <Providers>{children}</Providers>
          <ToastContainer />
        </Suspense>
      </body>
    </html>
  );
}
